### ISSUE TITLE
Deprecation Warning: sklearn.externals.joblib

### ISSUE THREAD

**Issue by Deathn0t** [deephyper/deephyper#12]
```
DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip insta    ll joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
```

**Comment by ilamaheshwari** [comment]
sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. This PR adds joblib as an explicit dependency.

joblib 0.10.3 is used as the minimum version since it is the version included in scikit-learn 0.18.1.
https://github.com/scikit-learn/scikit-learn/blob/a5ab948cbc366d705b1f8db8687c7162f51de22d/sklearn/externals/joblib/__init__.py#L119
