### ISSUE TITLE
[BUG] DeepHyper 101 Tutorial in Colab: error installing particular version of ray

### ISSUE THREAD

**Issue by BethanyL** [deephyper/deephyper#137]
**Describe the bug**
I ran the DeepHyper 101 tutorial in Colab and got an error on the line "!pip install ray==1.9.2 -I" 

"ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.8.2+zzzcolab20220527125636 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.21.1 which is incompatible...."
(Full error attached with screenshot.)

**To Reproduce**
1. Go to the DeepHyper 101 tutorial: https://deephyper.readthedocs.io/en/latest/tutorials/tutorials/colab/DeepHyper_101.html
2. Use the "Open in Colab" button.
3. Run the first cell.
Note: I got an error with the default runtime or when starting over with a new notebook using the GPU runtime.

**Expected behavior**
Successfully running the tutorial. 

**Screenshots**
<img width="1601" alt="DeepHyperError" src="https://user-images.githubusercontent.com/9046040/172243722-21e8f044-0c7e-4f76-8379-2b228eae072b.png">

**Desktop (please complete the following information):**
 Google Colab environment (either default runtime or GPU runtime).

**Additional context**
I tried removing the line to install Ray 1.9.2 separately and the tutorial seemed to work fine. (Installing DeepHyper installed Ray 1.12.1.)

**Comment by Deathn0t** [comment]
Thank you @BethanyL for reporting. This issue has been observed a few times already, at some point it was happening when doing `pip install ray` and we noticed by doing `pip install ray==1.9.2 -I`  that the issue was resolved but apparently it shows up again now...
Recently I removed `ray` evaluator from DeepHyper 101 to avoid having this type of disagreement with the first tutorial, see https://github.com/deephyper/tutorials/blob/779fcaec8f03ef58832529d4c9f7bb381466f4d5/tutorials/colab/DeepHyper_101.ipynb.
Also I re-replaced `pip install ray==1.9.2 -I` as suggested in your comment, see https://github.com/deephyper/tutorials/blob/99405c2ba9d6706816c64a5b007cbf8dbeacc4db/tutorials/colab/HPS_basic_classification_with_tabular_data/notebook.ipynb.

All of this in `develop` branch for now both for DeepHyper and Tutorials, it should be pushed to main soon.
