### ISSUE TITLE
[FAQ] Running Asyncio during NAS search

### ISSUE THREAD

**Issue by OliVandy** [deephyper/deephyper#155]
I am working in the Argonne conda/2022-07-01 environment on ThetaGPU. The issue involves running over multiple nodes using MPI, I am running into an error with Asyncio.

The exact error is 
`ValueError: Set of coroutines/Futures is empty.`
The error file is provided below which includes the traceback. The output file is also provided which shows that it is completing the previous steps in the code successfully.

At this point the main goal is to complete this NAS search and from what I can tell most of the pieces should be in place once this issue is fixed.

[10097925.error.txt](https://github.com/deephyper/deephyper/files/9284490/10097925.error.txt)
[10097925.output.txt](https://github.com/deephyper/deephyper/files/9284491/10097925.output.txt)
[transformer_NAS_mpiadj.txt](https://github.com/deephyper/deephyper/files/9284492/transformer_NAS_mpiadj.txt)

**Comment by Deathn0t** [comment]
Hello @OliVandy could you please provide the submission script used to launch the `transformer_NAS_mpiadj.py`

**Comment by OliVandy** [comment]
Absolutely! It is these two scripts.
[activate-dhenv.txt](https://github.com/deephyper/deephyper/files/9293725/activate-dhenv.txt)
[transformer_NAS_mpisc.txt](https://github.com/deephyper/deephyper/files/9293726/transformer_NAS_mpisc.txt)

**Comment by Deathn0t** [comment]
Hello @OliVandy, I found the source of the issue. It is due to a bad handling of the `timeout` criteria for the random-search inside the deephyper code. I fixed it and sent the commit to develop branch d18d760fe15c86c1b4d9b1242f8bf2a427252c9f. This update will not directly be updated on ThetaGPU has I need to perform more tests. In the mean time, you can use the `search.search(max_evals=100)` instead of `timeout` it should work this way and you don't need to change your current installation/setup.

**Comment by Deathn0t** [comment]
Hello @OliVandy can you let me know if this resolved the problem?
