### ISSUE TITLE
[Bug] Deprecated max_features="auto" in RandomForestRegressor causes UnboundLocalError in sklearn versions >=1.3

### ISSUE THREAD

**Issue by davdma** [deephyper/deephyper#212]
### Describe the Bug

[This line](https://github.com/deephyper/deephyper/blob/92b8bf9d0538b5b39a7e961f2cefedb64fdc9300/deephyper/skopt/learning/forest.py#L235C1-L235C29) of `RandomForestRegressor` class in **deephyper/deephyper/skopt/learning/forest.py** causes problems in conjunction with newer versions of sklearn 1.3.0 and above. The `max_features="auto"` parameter was deprecated and [ultimately removed in sklearn 1.3.0](https://github.com/scikit-learn/scikit-learn/pull/25941), so that instantiating a tree from sklearn using such a default parameter causes the `self.max_features` variable to fall through a gap in their conditional statements. The result is that the `max_features` variable is not instantiated and a `UnboundLocalError` thrown when it is later referenced in the sklearn source code.

The error can be replicated by installing sklearn version 1.3.0 and above and instantiating `CBO` with `surrogate_model="RF"` and calling method `fit_surrogate(df)`. The error is shown below:

![error](https://github.com/deephyper/deephyper/assets/42689743/a21561be-47aa-4c2a-b3d7-c0a9de9b8508)

### Describe Your Proposed Solution

The current documentation should specify that the RF surrogate model will not work with sklearn versions 1.3.0 and above. Else, the code needs to remove the deprecated `max_features="auto"` parameter. I suggest setting the default to `max_features=None` which in sklearn would have the same behavior as with the earlier versions.

**Comment by Deathn0t** [comment]
Hello @davdma , thank you for opening this issue with such a complete description!

Related to https://github.com/deephyper/deephyper/issues/209

For `deephyper==0.6.0` currently the latest release on PyPI, yes `pip install scikit-learn<1.3` resolves the issue.

Now, the issue was resolved in the `develop` branch: https://github.com/deephyper/deephyper/tree/develop

If you want to use `scikit-learn>=1.3` (should also work with `scikit-learn<1.3` ), you can install deephyper with the following command:

```console
pip install "deephyper[hps] @ git+https://github.com/deephyper/deephyper@develop"
```

Let me know if you have other questions.
