### ISSUE TITLE
[FAQ] How to reproduce AutoDEUQ (Automated Deep Ensemble with Uncertainty Quantification) For Regression with DeepHyper 0.8.0

### ISSUE THREAD

**Issue by RinnetenseiQ** [deephyper/deephyper#224]
**Context**
Can you provide library requirements for running examples in your docs?
I`m interesting in tutorial number 7
https://deephyper.readthedocs.io/en/latest/tutorials/tutorials/notebooks/07_NAS_with_Ensemble_and_UQ/tutorial_07.html
I have tried to run this notebook on Colab, using default version of required libraries, but fail. I got a lot of errors inside dh/tf/keras sources
I also tried to fix it. E.g. in chapter
"Adding Uncertainty Quantification to the Baseline Neural Network"
substitution "tf.keras" by "tf_keras" helps me. But when I going to ensemble chapter I got another errors inside UQBaggingEnsembleRegressor class
I think that issues related to dependency incompatibility and I want to know what version of libraries were used in this examples 

**Describe the task you are trying to achieve.**
A clear and concise description of what the task is.

**Describe the solution you'd like**

**Comment by Deathn0t** [comment]
Hello @RinnetenseiQ ,

How did you end up with the link to this tutorial? 

I am asking because on today's website the tutorial is not available on the tutorial page anymore as you can see here: https://deephyper.readthedocs.io/en/latest/tutorials/index.html

The upgrade between `tf.keras` and `tf_keras` because of Keras 3 was an issue.

Also, since `deephyper==0.8.0` the ensemble and nas were significantly changed ([See DeepHyper 0.8.0 - Changelog](https://github.com/deephyper/deephyper/releases/tag/0.8.0)). Ensembles are now more generic (compatible with more parallel backends, ML libraries, ML tasks such as regression/classification). NAS was reframed under the hyperparameter optimization framework (allowing the same capabilities as before with better compatibility with other ML frameworks and training pipelines). 

If you want to use the outdated API  using: `tensorflow~=2.16 tensorflow-probability==0.24.0` should work.

I you want to try the new API (the best):
- A tutorial on Neural architecture search: [6. Neural Architecture Search with Tensorflow/Keras2 (Basic)](https://deephyper.readthedocs.io/en/latest/tutorials/tutorials/colab/NAS_basic_tf_keras2.html)
- A tutorial on ensembling: [2. Hyperparameter Optimization for Tree Ensemble with Uncertainty Quantification (Scikit-Learn)](https://deephyper.readthedocs.io/en/latest/tutorials/tutorials/notebooks/07_HPO_and_UQ_Ensemble_ScikitLearn/tutorial.html)

Let me know if this helps!

**Comment by RinnetenseiQ** [comment]
> How did you end up with the link to this tutorial?
I dont remember already. I think, just going through docs

> The upgrade between `tf.keras` and `tf_keras` because of Keras 3 was an issue.
Is it mean that I should use `tf_keras` instead `tf.keras` in any cases that related to deephyper?


I will try your advices about NAS problem and let you know if something will go wrong.
About ensembling. I am interesting in approaches of uncertainty calculation for regresion task that related to ensemble creation. And I also think the prediction by distribution layer was also interesting trick. Is it possible to reproduce this using latest version of libraries?
